### ISSUE TITLE
Testing handle case sensitivity

### ISSUE THREAD

**Issue by matthewmccullough** [crichID/crichID.github.io#1]
@matthewMCCULLOUGH

@crichid

@crichID

**Comment by matthewmccullough** [comment]
![image](https://cloud.githubusercontent.com/assets/24734/26026737/deb77dac-37b5-11e7-8504-dc1d40e40174.png)

**Comment by matthewmccullough** [comment]
See https://github.com/github/services/pull/3280#issuecomment-300351384, where it highlights the handle properly on the desktop edition of the site:

![image](https://cloud.githubusercontent.com/assets/24734/26026742/11d27c14-37b6-11e7-9a96-5d1a3bb44e2b.png)

**Comment by nathos** [comment]
@crichid just another @mention test!
